### ISSUE TITLE
No way to specify environment variables like TOTAL_BANDWIDTH

### ISSUE THREAD

**Issue by justin-himself** [ich777/docker-rustdesk-server-aio#1]
According to the [rustdesk readme](https://github.com/rustdesk/rustdesk-server), hbbs and hbbr can be configured using these ENV variables. You can specify the variables as usual or use an .env file. For example,

| variable | binary | description |
| --- | --- | --- |
| TOTAL_BANDWIDTH | hbbr | max total bandwidth (in Mb/s) |

However, there's no way to specify the environment variables via docker. The `HBBR_PARAMS` and `HBBS_PARAMS` are useless as these environment variables cannot be attached as parameters after the executable.

```bash
root@840d8e9025f3:/# hbbr --help
hbbr 1.1.8
Purslane Ltd. <info@rustdesk.com>
RustDesk Relay Server

USAGE:
    hbbr [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -k, --key <KEY>                       Only allow the client with the same key
    -p, --port <NUMBER(default=21117)>    Sets the listening port
```

**Comment by ich777** [comment]
> However, there's no way to specify the environment variables via docker.

Why shouldn't you be able to add a environment variable to Docker? The `.env` file is just the file with the environment variables for `docker-compose`.
Why not specify it as a `env` variable in the `docker run` command? This should have the exact same outcome or am I wrong about that?

Are you using the container on Unraid or another Host? If you are using Unraid simply click on  `Add another Path, Port, Variable, Label or Device` in the template -> configure it something like that:
![grafik](https://github.com/ich777/docker-rustdesk-server-aio/assets/28066518/b4676bfb-457d-44b7-a8f6-a77ca77d00a6)
click `Add` -> `Apply`

If you are using another Host than Unraid simply add something like this to your docker run command: `--env 'TOTAL_BANDWIDTH=50'` (in this specific case the bandwidth is limited to 50Mb/s)

**Comment by justin-himself** [comment]
Sorry, forget about env in docker 😰
