### ISSUE TITLE
Unable to run docker container

### ISSUE THREAD

**Issue by josurr** [ich777/docker-rustdesk-server-aio#2]
Trying to run the AiO Rust Desk server docker container on an Ubuntu Server VM 22.04.4 and am receiving the following error when trying to start the container: 

> Apr 17 02:10:24 proxmox-dockervm systemd[1]: Starting rustdesk AIO server...
> Subject: A start job for unit docker-compose-rustdesk_server.service has begun execution
> Defined-By: systemd
> Support: http://www.ubuntu.com/support
> 
> A start job for unit docker-compose-rustdesk_server.service has begun execution.
> 
> The job identifier is 5165.
> Apr 17 02:10:30 proxmox-dockervm docker[9137]: services.rustdesk-server-aio.environment.[1]: unexpected type map[string]interface {}
> Apr 17 02:10:30 proxmox-dockervm systemd[1]: docker-compose-rustdesk_server.service: Main process exited, code=exited, status=15/n/a
> Subject: Unit process exited
> Defined-By: systemd
> Support: http://www.ubuntu.com/support
> 
> An ExecStart= process belonging to unit docker-compose-rustdesk_server.service has exited.
> 
> The process' exit code is 'exited' and its exit status is 15.
> Apr 17 02:10:30 proxmox-dockervm systemd[1]: docker-compose-rustdesk_server.service: Failed with result 'exit-code'.
> Subject: Unit failed
> Defined-By: systemd
> Support: http://www.ubuntu.com/support
> 
> The unit docker-compose-rustdesk_server.service has entered the 'failed' state with result 'exit-code'.
> Apr 17 02:10:30 proxmox-dockervm systemd[1]: Failed to start rustdesk AIO server.

I am not seeing anything that corresponds to the defined error "unexpected type map[string]interface {}" in my docker-compose.yml file:

> name: rustdesk-server-aio
> services:
>     rustdesk-server-aio:
>         container_name: RustDeskServer-AiO
>         network_mode: host
>         environment:
>             - TZ=America/Phoenix
>             - HBBS_ENABLED: "true"
>             - HBBS_PARAMS: "--key _"
>             - HBBR_ENABLED: "true"
>             - HBBR_PARAMS: "--key _"
>             - uid: "99"
>             - uid: "100"
>             - DATA_PERM: 770
>             - UMASK: 000
>         ports:
>             - "21115:21115/tcp"
>             - "21116:21116/tcp"
>             - "21117:21117/tcp"
>             - "21118:21118/tcp"
>             - "21119:21119/tcp"
>             - "21116:21116/udp"
>         volumes:
>             - /mnt/data_storage/appdata/rustdeskserver-aio:/rustdesk-server:rw
>         restart: unless-stopped
>         image: "ich777/rustdesk-server-aio"

I copied the docker config command from unRAID and cleaned it up using the Composerize website

**Comment by ich777** [comment]
> > - uid: "99"
> > - uid: "100"

Hi, I'm not 100% sure if I can help since I'm not very familiar with Proxmox but these two environment variables are definitely wrong.
You have to use `UID` followed by the UID from a user that is allowed to use the Docker service and write data (on Unraid it's 99 or on Debian/Ubuntu it's 1000), the same goes for the second variable, it should be actually be `GID` followed by a GID from a user that is allowed to use the Docker service and write data (on Unraid that's 100 or on Debian/Ubuntu it's 1000).

**Comment by josurr** [comment]
Found the issues:

In addition to your finding of the "uid" value being defined twice (the second time had been changed from "gid" to "uid" accidentally), when I had converted from the unRAID docker run command style syntax to docker compose, the environment variables for HBBS/HBBR_ENABLED and HBBS/HBBR_PARAMS were swapped from '=' to ':' and the values for each variable were encapsulated in ""

After reverting the variable lines back to '=' and removing the "" around the values, the service is running now.

Here is the contents of the working docker-compose.yml file:

> name: rustdesk-server-aio
> services:
>     rustdesk-server-aio:
>         container_name: rustdesk-server-aio
>         network_mode: host
>         environment:
>           - TZ=America/Phoenix
>           - HBBS_ENABLED=true
>           - HBBS_PARAMS=--key _
>           - HBBR_ENABLED=true
>           - HBBR_PARAMS=--key _
>           - uid:"99"
>           - gid:"100"
>           - DATA_PERM:"770"
>           - UMASK:"000"
>         ports:
>           - "21115:21115/tcp"
>           - "21116:21116/tcp"
>           - "21117:21117/tcp"
>           - "21118:21118/tcp"
>           - "21119:21119/tcp"
>           - "21116:21116/udp"
>         volumes:
>           - /mnt/data_storage/appdata/rustdeskserver-aio:/rustdesk-server:rw
>         restart: unless-stopped
>         image: "ich777/rustdesk-server-aio"

**Comment by ich777** [comment]
@josurr please note that the environment variables are case sensitive so to speak you have to use `UID` and `GID` not `uid`/`gid` but in your case it wouldn't matter because the two variables default to `99`/`100`
