### ISSUE TITLE
Latest release causes a "key mismatch" error

### ISSUE THREAD

**Issue by jessielw** [ich777/docker-rustdesk-server-aio#3]
I find if I manually add the pub key that is generated in the docker server in the client it works, but this wasn't how it was before. You could just provide the ID/Relay server and connect without passing a key.

**Comment by ich777** [comment]
> I find if I manually add the pub key that is generated in the docker server in the client it works, but this wasn't how it was before.

This should definitely be the way that it should be if you pass over these arguments:
![grafik](https://github.com/ich777/docker-rustdesk-server-aio/assets/28066518/20792031-2758-4f80-81a2-1347d17a9840)


However if you remove `--key _` from both variables you shouldn't need a key, but I would strongly recommend to use a key since using it without a key could be maybe be a security risk and enables anyone to use your server.

**Comment by ich777** [comment]
BTW, something similar was reported [here](https://forums.unraid.net/topic/83786-support-ich777-application-dockers/?do=findComment&comment=1423486).

**Comment by ich777** [comment]
@jessielw any comment on that?

**Comment by ich777** [comment]
Oh, I just discovered this comment:
https://github.com/rustdesk/rustdesk-server/issues/417#issuecomment-2132234422

If you really want to use the container without any key then you have to use it like that:
`--key ""`

**Comment by jessielw** [comment]
> > I find if I manually add the pub key that is generated in the docker server in the client it works, but this wasn't how it was before.
> 
> This should definitely be the way that it should be if you pass over these arguments: ![grafik](https://private-user-images.githubusercontent.com/28066518/336573369-20792031-2758-4f80-81a2-1347d17a9840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzA0MzMsIm5iZiI6MTcxNzYzMDEzMywicGF0aCI6Ii8yODA2NjUxOC8zMzY1NzMzNjktMjA3OTIwMzEtMjc1OC00ZjgwLTgxYTItMTM0N2QxN2E5ODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDIzMjg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZDEwMTIyZTNkMDMyMjYzYmYzNWU2MzM0NDUxNjI1N2Q3Mjc3Yzg3NjRjODAyZjE1N2MyYjIyYmRhODUyNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GFUydik6gZDm6pNsSVQNiY0wZHOgD3OuPdgDXcwoKv4)
> 
> However if you remove `--key _` from both variables you shouldn't need a key, but I would strongly recommend to use a key since using it without a key could be maybe be a security risk and enables anyone to use your server.

I don't mind using it with the key. I just thought something was wrong because when I initially started using it, it didn't require the key. I used it for a *long* time now off of your template and it just worked without passing the key. 

My template doesn't have the above options.
Again, I don't mind using the key, I just thought something was wrong with the template/image.

**Comment by ich777** [comment]
You can simply add the variables to your template and use RustDesk without a key but I really don‘t recommend doing it that way because it‘s a security risk.

I‘ll close this issue since this seems to be solved, if you got any further issues feel free to open up a new issue.

**Comment by jessielw** [comment]
> You can simply add the variables to your template and use RistDesk without a key but I really don‘t recommend doing it that way because it‘s a security risk.
> 
> I‘ll close this issue since this seems to be solved, if you got any further issues feel free to open up a new issue.

Thanks for taking the time and letting me know. I appreciate it!

**Comment by kpimichael** [comment]
I too am having problems with the key mismatch error.   I reinstalled the latest release and manually copied the keys as suggested in thread...and it still gives the same message.   Argh...  I was becoming very dependent on RustDesk and this unnerves me that something like this is not quickly resolved.

UPDATE:   I reinstalled and copied the keys to all clients and it worked!   Not sure what changed, but it worked the second time for me.   I am on self hosted environment 1.1.11-1 docker version 2.20.2

**Comment by ich777** [comment]
@kpimichael as daid above it is always a bad idea to not enter a key since everybody could connect to your server and also your clients (granted if they have the IDs and passwords).

However you usually don‘t have to reinstall the clients, seems that something else was wrong.
