### ISSUE TITLE
Latest release(1.1.12) causes a "key mismatch" error

### ISSUE THREAD

**Issue by Hades-ming** [ich777/docker-rustdesk-server-aio#4]
First of all thank you for making such a good software, you are really great. But I think I ran into a bug. I made sure I entered the correct IP and pub contents, and the home page also said "Ready". The message "key mismatch" was displayed when I tried to connect. If this is a bug please fix it, if not please tell me what is wrong. Please let me know if there is any more information I can provide.
![image](https://github.com/user-attachments/assets/9c69f9db-fbf3-4770-893a-9b7269b32f2e)

**Comment by Hades-ming** [comment]
My cloud server system is Alpine, here are my installation steps.
#### 1.2 Downloading the file

Connect to the Server over ssh and download the RustDesk Server file. [RustDesk Server lot release address] (https://github.com/rustdesk/rustdesk-server/releases).

``` bash
# in the /usr/local/ directory
cd /usr/local/
# Use wget to download version 1.1.8-2 (the latest version can be found at the above release address)
Wget HTTP: / / https://github.com/rustdesk/rustdesk-server/releases/download/1.1.12/rustdesk-server-linux-amd64.zip
# unzip
unzip rustdesk-server-linux-amd64.zip
# Rename the decompressed file (easy to manage)
mv amd64 rustdesk
` ` `

### 2. Edit OpenRC service files

#### 2.1 Edit the 'hbbs' service file

Create or edit the '/etc/init.d/hbbs' file:

```bash
nano /etc/init.d/hbbs
` ` `

Add the following to the file and make sure the path points to '/usr/local/rustdesk/hbbs' :

```bash
#! /sbin/openrc-run

command="/usr/local/rustdesk/hbbs"
command_background=true
pidfile="/var/run/hbbs.pid"
name="HBBS Service"

depend() {
need net
}
` ` `

#### 2.2 Edit the hbbr service file

Create or edit the '/etc/init.d/hbbr' file:

```bash
nano /etc/init.d/hbbr
` ` `

Add the following to the file and make sure the path points to '/usr/local/rustdesk/hbbr' :

```bash
#! /sbin/openrc-run

command="/usr/local/rustdesk/hbbr"
command_background=true
pidfile="/var/run/hbbr.pid"
name="HBBR Service"

depend() {
need net
}
` ` `

### 3. Grant execution permission

Give execute permissions to these two service files:

```bash
chmod +x /etc/init.d/hbbs
chmod +x /etc/init.d/hbbr
` ` `

### 4. Start and add the service to boot

#### 4.1 Starting the Service

Start 'hbbs' and' hbbr 'with the following command:

```bash
rc-service hbbs start
rc-service hbbr start
` ` `

#### 4.2 Adding a Service to Start on

Add services to the default run level to ensure they run automatically at startup:

```bash
rc-update add hbbs default
rc-update add hbbr default
` ` `

5. Verify that the service is started

After restarting with reboot, run the following command to check the status of the service:

```bash
rc-service hbbs status
rc-service hbbr status
` ` `

**Comment by ich777** [comment]
@Hades-ming Did you solve your issue?

May I ask why do you post steps for the manual installation?

The container includes both `hbbs` and `hbbr` and is working out of the box as long as you are using the correct key on the clients that is displayed in the Docker logs for the container.

The container is just working fine for me and many others, do you intend to not use a key (which I would not recommend)?

**Comment by Hades-ming** [comment]
> @Hades-ming Did you solve your issue?
> 
> May I ask why do you post steps for the manual installation?
> 
> The container includes both `hbbs` and `hbbr` and is working out of the box as long as you are using the correct key on the clients that is displayed in the Docker logs for the container.
> 
> The container is just working fine for me and many others, do you intend to not use a key (which I would not recommend)?

I am very sorry that I wanted to raise Issues for the project **rustdesk-server**, and accidentally clicked the wrong point and raised issues here. Now I've turned it off.
I haven't solved the problem yet. I post my installation steps in case I make a mistake and I don't realize it, giving my installation steps also helps developers locate bugs. I did not use docker installation, so I could not use the solution you gave, but he gave me some ideas, I tried to find the manual installation log, the result failed, I could not find the manual installation log where to view.
